### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by dsitarek** [nss-evening-cohort-16/gitsub-the-fighting-mongooses#31]

**Comment by Nissa2424** [comment]
Name of Project:  

- The Fighting Mongooses 

Overview of Project: 

-  Create a Project board for The Fighting Mongooses site and make columns for 'Backlog', 'Todo', 'Doing', 'Code Review', 
-  'Done'. Create notes for different units of work, make the notes into issues, and assign it to the team members doing the 
-   work. When you are assigned to an issue, make sure that you are moving it over to the right column on the board.

 Link to your wireframes/prototype: 
- [https://testlink.org/]

Link to the deployed project (will learn in week 5):
 ---> project goes here 

Link to your project board (yes...even though it is a part of the repo):

- https://github.com/nss-evening-cohort-16/gitsub-the-fighting-mongooses/blob/main/instructions.md

Description of the user: 

List of features: 

Screenshots of your project: 
List of contributors and links to their GH profiles: 
- Daniel Sitarek 
- David Vareba 
- Harika

**Comment by Nissa2424** [comment]
@hcodes11 @davidvareba @dsitarek  - this Readme file is not complete I just added a basic template to update later.

**Comment by Nissa2424** [comment]
Done and pushed
